package:
  name: clipp
  version: 1.0.3

source:
  git_url: https://github.com/muellan/clipp.git
  git_rev: v1.0.3

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

